//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticoA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public int id_auto { get; set; }
        public string patente { get; set; }
        public string color { get; set; }
        public string descripcion { get; set; }
        public int id_modelo { get; set; }
        public string foto { get; set; }
    
        public virtual Modelo Modelo { get; set; }
    }
}
